### ISSUE TITLE
Undefined token

### ISSUE THREAD

**Issue by Ivanrenes** [glebbash/nestjs-fireorm#11] opened 2024-03-25 02:12 UTC
<img width="876" alt="Screenshot 2024-03-24 at 9 11 20 PM" src="https://github.com/glebbash/nestjs-fireorm/assets/34603733/54d1c956-3f34-49a8-b445-b2cdf7732771">

No sure what's going on

**Comment by glebbash** [comment] 2024-03-25 10:44
Can you provide minimal reproduction?

**Comment by mrbatista** [comment] 2024-03-26 10:26
@glebbash same problem from me.
This is related to decorator metadata.
NestJS check for metadata `design:type`
Fireorm check form metadata `design:paramtype`

If change to `design:type` application start

**Comment by Ivanrenes** [comment] 2024-03-26 10:28
Interesting, will check, I supposed I the issue is related to reflector-metadata lib then I tried to downgrade but didn't work, will check that, thanks!

**Comment by mrbatista** [comment] 2024-03-26 10:33
@Ivanrenes related to https://github.com/rbuckton/reflect-metadata/issues/160?

**Comment by glebbash** [comment] 2024-03-26 10:37
I've seen issues upgrading to latest `reflect-metadata` as well.

> If change to `design:type` application start

@mrbatista can you provide more info on this so I could add it to the lib.

**Comment by Ivanrenes** [comment] 2024-03-26 10:44
> @Ivanrenes related to https://github.com/rbuckton/reflect-metadata/issues/160?

Yes

**Comment by mrbatista** [comment] 2024-03-26 11:54
> I've seen issues upgrading to latest `reflect-metadata` as well.
> 
> > If change to `design:type` application start
> 
> @mrbatista can you provide more info on this so I could add it to the lib.

I'm trying to understand the problem:
Package **@nest/common** has moved `reflect-metadata` to **peerDependecies** https://github.com/nestjs/nest/blob/ddc1265735bdec0f2e1dc4ac19d98304692b841a/packages/common/package.json#L28 and allow 0.1.0 and 0.2.0 dependency.
My dependencies tree is correct:
![Screenshot 2024-03-26 alle 12 12 54](https://github.com/glebbash/nestjs-fireorm/assets/6544817/c0f1cf77-f662-4d5c-88f7-222298ea0d68)
**fireorm** library has peerDependency to ^0.1.13 https://github.com/wovalle/fireorm/blob/7305cbbe7c32f12d9e932abf3ed5c79f06891373/package.json#L78 which forces you to stay on version 0.1.*

nest check at [this line](https://github.com/nestjs/nest/blob/ddc1265735bdec0f2e1dc4ac19d98304692b841a/packages/common/decorators/core/inject.decorator.ts#L40) for metadata `design:type`.
FireormService has different metadata (line 36):
![Screenshot 2024-03-26 alle 12 53 33](https://github.com/glebbash/nestjs-fireorm/assets/6544817/2a6c5d5b-13bc-45d8-8afd-a80a3a3a8220)

**Comment by mrbatista** [comment] 2024-03-27 09:24
> Interesting, will check, I supposed I the issue is related to reflector-metadata lib then I tried to downgrade but didn't work, will check that, thanks!

@Ivanrenes any news?

**Comment by DiegoAsadurian** [comment] 2024-03-27 15:14
Hello, i have the same issue.
Could anyone find a way to solve it?

**Comment by glebbash** [comment] 2024-03-27 16:03
I managed to fix it in a sample project. The issue is in `@nestjs/common@10.3`.

Doing this should fix the issue:
```bash
npm i @nestjs/common@~10.2.10
```

**Comment by glebbash** [comment] 2024-03-27 16:09
Seems like this PR is the cause of the issue: https://github.com/nestjs/nest/pull/13056

**Comment by Ivanrenes** [comment] 2024-03-27 18:59
@glebbash absolutely, that's the issue

**Comment by glebbash** [comment] 2024-03-28 11:29
[PR was reverted](https://github.com/nestjs/nest/pull/13370), now `npm i @nestjs/common@latest` will work too.

**Comment by glebbash** [comment] 2024-03-28 11:31
Closing this now. Thanks everyone for reporting and helping to find the issue. 💪

**Closed as completed by glebbash** 2024-03-28 11:31 UTC
